import type { Metadata } from "next";
import "./globals.css";
import { Cormorant_Garamond } from "next/font/google";
import { getLocale } from "next-intl/server";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-cormorant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body className={`${cormorant.variable} antialiased bg-muted text-[oklch(25%_0.03_145)]`}>
        {children}
      </body>
    </html>
  );
}
